Repository C2FO/gofigure, pull requests merged in 2021-06, with the labels that each got.

#25 Fix incorrect TS type in comment
  lib/index.js
Labels: size/XS

#26 chore: Update dependencies
  .eslintrc.js
  .github/workflows/test.yml
  .gitignore
  .jshintrc
  .nvmrc
  .prettierrc.json
  .run/jest.run.xml
  .run/test.run.xml
  .travis.yml
  jest.config.js
  lib/PatternEventEmitter.js
  lib/helpers.js
  lib/index.js
  lib/loader/FileLoader.js
  lib/loader/index.js
  lib/loader/loaderHelpers.js
  lib/processor/index.js
  lib/processor/merger.js
  lib/processor/mixin.js
  lib/processor/processorHelper.js
  lib/processor/replacer.js
  lib/processor/selector.js
  package-lock.json
  package.json
  test/__fixtures__/config-etcd/gofigure_queries.json
  test/__fixtures__/config-etcd/queries.json
  test/__fixtures__/config-mixin/config-mixin.default.json
  test/__fixtures__/config-mixin/config-mixin.development-one.json
  test/__fixtures__/config-mixin/config-mixin.development-two.json
  test/__fixtures__/config-mixin/config-mixin.production-one.json
  test/__fixtures__/config-mixin/config-mixin.production-two.json
  test/__fixtures__/config-mixin/development.mixin.json
  test/__fixtures__/config-mixin/production.mixin.json
  test/__fixtures__/configs/config-env-var/config.json
  test/__fixtures__/configs/config-env/config.json
  test/__fixtures__/configs/config-shared-env/config.json
  test/__fixtures__/configs/configs1/config1.json
  test/__fixtures__/configs/configs2/config2.json
  test/__fixtures__/index.js
  test/gofigure.spec.js
  test/gofigure.test.js
  test/helper.js
  test/loader/FileLoader.spec.js
  test/loader/FileLoader.test.js
  test/processor/merger.spec.js
  test/processor/merger.test.js
  test/processor/replacer.spec.js
  test/processor/replacer.test.js
Labels: size/XXL

#27 v2.0.0
  HISTORY.md
  package.json
Labels: size/S

#29 chore: remove etcd references
  README.md
  lib/index.js
  lib/loader/index.js
  test/__fixtures__/config-etcd/gofigure_queries.json
  test/__fixtures__/config-etcd/queries.json
Labels: size/XXL

#32 chore: update renovate to automerge dev dependencies
  renovate.json
Labels: size/S

#33 chore: remove coveralls dependency
  package.json
Labels: size/XS

#38 chore : move to conventional commits
  .commitlintrc.json
  .husky/.gitignore
  .husky/commit-msg
  .releaserc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XXL

#40 fix: issue where configs were not properly merging multiple locations
  .gitignore
  lib/index.js
  lib/processor/index.js
  lib/processor/mixin.js
  lib/processor/processor.js
  lib/processor/selector.js
  test/__fixtures__/config-mixin/config-mixin.default.json
  test/__fixtures__/config-mixin/config-mixin.development-one.json
  test/__fixtures__/config-mixin/config-mixin.development-two.json
  test/__fixtures__/config-mixin/config-mixin.production-one.json
  test/__fixtures__/config-mixin/config-mixin.production-two.json
  test/__fixtures__/config-mixin/development.mixin.json
  test/__fixtures__/config-mixin/production.mixin.json
  test/__fixtures__/configs-with-mixins.js
  test/__fixtures__/configs.js
  test/__fixtures__/configs/config-env-var/config.json
  test/__fixtures__/configs/config-env/config.json
  test/__fixtures__/configs/config-shared-env/config.json
  test/__fixtures__/configs/configs1/config1.json
  test/__fixtures__/configs/configs2/config2.json
  test/__fixtures__/helpers.js
  test/__fixtures__/index.js
  test/gofigure.spec.js
  test/loader/FileLoader.spec.js
Labels: size/XXL
